name : Node.js CI

on: [push]

jobs:
  day2job:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 14

    steps:
      - name: checkout repository
        uses: action/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Run a script
        run: echo "xin chao Hao"
        
      - name: Check nodeverson
        run: node -v

    
    
